### ISSUE TITLE
Production questions

### ISSUE THREAD

**Issue by ToBeReplaced** [adelton/docker-freeipa#1]
I'm evaluating FreeIPA for a new project (micro-installation, 10 users, 15 machines)  and am looking at running it from inside of a docker instance in production.

I'm willing to work through bugs and dragons, but is there anything you know of that is currently a show-stopper for doing this?

I'm new to FreeIPA, so I might be entirely off -- Here's what I'm worried about on first inspection:
1) It looks like we need to expose 7389, 9443, 9444, 9445 for replication and server-server communication.
2) Passwords need to be passed in over the command-line. We could do a little better by reading them from files that we mount to the container so that they only show in the command that's internal to the container as opposed to on the host.
3) We don't expose a meaningful process to the docker host for sending signals to via docker kill.
4) We run an ssh server (maybe remove?)
5) We have to workaround systemctl
6) ntpd in the container

Any insights into what are or will be problems would be helpful. I'd also be happy to help out if there's anything on the roadmap that is open to outside contributors.

Cheers,
ToBeReplaced

**Comment by sirtaj** [comment]
Related to production use, I would be grateful for some explicit documentation on persistent storage locations, so that host volumes or data-only containers can be used for data used/served by the container. Some VOLUME directives in the Dockerfile would be a great start.

**Comment by adelton** [comment]
> Some VOLUME directives in the Dockerfile would be a great start.

Please check the master-test-volume branch for the current work in progress.

**Comment by adelton** [comment]
> Related to production use, I would be grateful for some explicit documentation on persistent storage locations, so that host volumes or data-only containers can be used for data used/served by the container. Some VOLUME directives in the Dockerfile would be a great start.

The branches were now updated with content supporting persistence. Please check the ```README``` for instructions.

**Comment by adelton** [comment]
> 4) We run an ssh server (maybe remove?)

This was now removed even from master since ```docker exec``` can be used for debugging now.

**Comment by adelton** [comment]
I'm going to close this issue because I believe the concerns have been addressed.

Please open separate (GitHub) issues for separate issues you might encounter or find outstanding.
