### ISSUE TITLE
ipa-replica-install / Feature Request: Replicas

### ISSUE THREAD

**Issue by ToBeReplaced** [adelton/docker-freeipa#11]
I have an existing IPA installation (all 3.3.3, CentOS 7).

I'd be interested in trying out a container for the next cell.

So, feature/container request: Ability to run an IPA server in a container that is a replica of an existing server.

**Comment by adelton** [comment]
> So, feature/container request: Ability to run an IPA server in a container that is a replica of an existing server.

It is now available in master and derived branches, as well as in the images in the Docker registry.

Use volume and put ```ipa-replica-install-options``` and the GPG-encrypted replica information file to the directory that you bind with ```-v``` before starting the container. The existence of ```ipa-replica-install-options``` will trigger ```ipa-repliace-install```.
