### ISSUE TITLE
Can I run freeipa-server WebUI on a custom port?

### ISSUE THREAD

**Issue by frol** [adelton/docker-freeipa#12]
I would like to use something like :4443 to access FreeIPA WebUI. Is it even possible?

**Comment by frol** [comment]
It seems there is no support for such use-case in `ipa-client-install`, but maybe there is another solution?

**Comment by adelton** [comment]
I'm afraid even if you could run the container with ```-p 4443:443```, the WebUI makes redirects to ```https:``` without port specified, so you'd be redirected out of your custom 4443 port pretty quickly.

The support would really need to be in ```ipa-server-install```.

In general, this is not really container specific, so I will advice to either file a ticket against FreeIPA at https://fedorahosted.org/freeipa/newticket, or talk to the FreeIPA team about your requirement on freeipa-users mailing list.

**Comment by frol** [comment]
Just for the history, I've found a related issue there: https://fedorahosted.org/freeipa/ticket/3955

**Comment by adelton** [comment]
> Just for the history, I've found a related issue there: https://fedorahosted.org/freeipa/ticket/3955

That however is about the communication that the IPA client makes, while you've asked for different port for WebUI.

**Comment by frol** [comment]
It is related in that way that ipa-client-install communicates with it via 443 port also...
See:
./ipa-client/ipa-join.c:    ret = asprintf(&url, "https://%s:443/ipa/xml", ipaserver);
./ipa-client/ipa-join.c:    ret = asprintf(&url, "https://%s:443/ipa/xml", ipaserver);

Probably, you are right I was not precise in my words. I want move all HTTP and HTTPS communication of FreeIPA to custom ports.
