### ISSUE TITLE
Warning when start

### ISSUE THREAD

**Issue by cybertk** [adelton/docker-freeipa#13]
```
Failed to create file /var/log/wtmp: No such file or directory
Failed to create file /var/log/btmp: No such file or directory
```

**Comment by adelton** [comment]
Thanks for the report. It looks like we call ```systemd-tmpfiles --remove --create``` too soon. I'll try to fix that.

**Comment by adelton** [comment]
Proposing fix: https://github.com/adelton/docker-freeipa/pull/15

**Comment by adelton** [comment]
Fixed in master and derived branches.
