### ISSUE TITLE
Can a client be enrolled to a server on the same host?

### ISSUE THREAD

**Issue by ToBeReplaced** [adelton/docker-freeipa#16]
I have a machine with two ip addresses, 12.34.56.1 and 12.34.56.2

I created a replica with the centos-7 image and ran it with `-p 12.34.56.2:80:80 ...`.

If I `ipa-client-install` on the machine outside of docker, the first line is:

`Skip replica.i.just.configured: cannot verify if this is an IPA server`

Then on ntp:

`Unable to sync time with IPA NTP server, assuming the time is in sync. Please check that 123 UDP port is opened.`

If I stop the replica container, the ntp issue disappears. My guess is that it has something to do with binding 0.0.0.0 instead of 12.34.56.1.

Is there a way to get the setup I am looking for? Perhaps shorter step is, is there a way to inform ipa to bind to a specific ip instead of 0.0.0.0?

**Comment by adelton** [comment]
> Perhaps shorter step is, is there a way to inform ipa to bind to a specific ip instead of 0.0.0.0?

Testing with a small Apache-only image, starting container as

```docker run -p 10.11.12.13:80:80 httpd```

and running

```
# netstat -tln | grep :80
tcp        0      0 10.16.96.111:80         0.0.0.0:*               LISTEN     
```

shows me that at least with docker-io-1.5.0-2.fc21.x86_64, the IP address value to ```-p``` is observed.

**Comment by ToBeReplaced** [comment]
I see the same behavior you observe. The container binds to the appropriate ip. However, this seems to prohibit an `ipa-client-install` outside of the container on the host machine.

**Comment by adelton** [comment]
How do you tell the host to IPA-enroll to the replica and to find the replica? By changing ```/etc/resolv.conf```?

Did you run the replica container with ```-e IPA_SERVER_IP=12.34.56.2```?

**Comment by ToBeReplaced** [comment]
Yes, the replica was run with `-e IPA_SERVER_IP=12.34.56.2`. No changes to `/etc/resolv.conf` were made on the host. I allowed for discovery to occur. The host found both a server on a remote machine and the replica on the host machine. The install skipped the replica with `Skip replica.i.just.configured: cannot verify if this is an IPA server`.

**Comment by adelton** [comment]
And if you try to ```ipa-client-install``` from different machine, does it work?

Also, I believe there is a log that could have some helpful information. Looking at the source code in ipadiscovery.py, this error message is emitted when no more specific error status is reported by self.ipacheckldap, so perhaps there are some debug messages in the log?

**Comment by ToBeReplaced** [comment]
I won't be able to test this for a little bit -- the setup above was already wiped. Thanks for the interest; I'll bump again when I have more time to recreate and print the debug messages.

**Comment by adelton** [comment]
Closing. Feel free to reopen or file new issue if you want to revisit.
