### ISSUE TITLE
disable forced HTTPS

### ISSUE THREAD

**Issue by joshuacox** [adelton/docker-freeipa#18]
I was pushing this into an instance of octohost ( http://octohost.io/ ).  But FreeIPA demands traffic from port 443.  Which is broken once octohost does all of it's routing.  I've modified octohost in the past so I could get force the routing of certain ports to a specific host:
https://github.com/octohost/octohost/pull/78/files
and I'm also the one who put the force SSL in place:
https://github.com/octohost/octohost/pull/113
and I've got a pull request that hasn't been merged yet to force alternate nginx configurations so I can give a container special configuration options

However, given all this i don't want to give port 443 and port 80 to my FreeIPA container, I want to dedicate those ports to the nginx reverse proxy so all the name based routing continues to work.  But, as you guys probably well understand, the SSL connection needs to be terminated at the nginx reverse proxy.   So what I need is to be able to specify a cert and key for the container upon starting up (and have those on the host for the proxy to use), and also to be able to disable the force SSL on the FreeIPA container (as SSL is being handled upstream by the nginx proxy).  There would'nt happen to be some ENV vars already you can specify for this?  If not, anyone have any pointers on where all I might run into issues trying to get FreeIPA to do such a thing (i.e. accept that SSL is handled upstream by the proxy and relax the rules a bit).

Or perhaps I'm going about this entirely wrong and someone has alternate suggestions, in any case I'd like to hear opinions.

**Comment by adelton** [comment]
I'm sorry but it's hard for me to understand what your setup actually is.

Can you describe just the container with FreeIPA server and if there's supposed to be something else in that container and what is its relationship to the other bits? The nature of the other bits is not that important (whether it is nginx or Apache, that does not matter), but *where* those are bits will live (in another container, on the host outside of container) is important.

**Comment by joshuacox** [comment]
The proxy bit itself (nginx) lives directly on octohost (not inside a container though that will change in the future it seems and it will also be in a container), all docker images are within the octohost, octohost is a sort of mini-heroku if you will.  You push a repo at it with a Dockerfile up top and it automatically builds the container.  Octohost happens to be a VM in this scenario that hosts docker containers, FreeIPA would be an equivalent docker image like any other on the host.  When built I can assign all the ports FreeIPA needs from the host VM directly to the FreeIPA docker container, with the exception of 443 and 80, those are already taken by the proxy (nginx), so a random highport is assigned to the FreeIPA container to route to it's port 80.  Then the proxy connects to the high assigned port when it gets traffic based on its name.  At this point FreeIPA does not like it as the proxy has terminated the SSL connection and is merely using port 80.

I think it all boils down to this, allow the FreeIPA docker instance to be configured to not force SSL and let port 80 traffic go without trying to force it 443.  I think setting an ENV var would be good for this, but I may be wrong.

**Comment by joshuacox** [comment]
sorry if it's all too confusing, I'm providing too much detail perhaps, note in this scenario everything is inside a single VM named octohost on this VM with one single IP there is a proxy (nginx).  And ignoring the other containers there is one container that has FreeIPA on it.  Here's what a `docker ps -l` looks like after it is started:

```
root@octo:~# docker ps -l
CONTAINER ID        IMAGE                     COMMAND                CREATED              STATUS              PORTS                                                                                                                                                                                                                                                                                                                  NAMES
a2bcb882b3c9        octoprod/freeipa:latest   "/bin/sh -c /usr/sbi   About a minute ago   Up About a minute   464/udp, 123/udp, 53/udp, 88/udp, 65.67.51.188:53->53/tcp, 0.0.0.0:88->88/tcp, 0.0.0.0:123->123/tcp, 0.0.0.0:389->389/tcp, 0.0.0.0:464->464/tcp, 0.0.0.0:636->636/tcp, 0.0.0.0:7389->7389/tcp, 0.0.0.0:9443->9443/tcp, 0.0.0.0:9444->9444/tcp, 0.0.0.0:9445->9445/tcp, 0.0.0.0:11080->80/tcp, 0.0.0.0:11443->443/tcp   sleepy_carson   
```

**Comment by adelton** [comment]
> When built I can assign all the ports FreeIPA needs from the host VM directly to the FreeIPA docker container, with the exception of 443 and 80, those are already taken by the proxy (nginx), so a random highport is assigned to the FreeIPA container to route to it's port 80.

You could still add the configuration of the nginx proxy to subrequest particular locations (```/ipa```?) to that high port to get to FreeIPA server in the container.

> Then the proxy connects to the high assigned port when it gets traffic based on its name. At this point FreeIPA does not like it as the proxy has terminated the SSL connection and is merely using port 80.

Why can't the proxy open another SSL connection to the container?
 
> I think it all boils down to this, allow the FreeIPA docker instance to be configured to not force SSL and let port 80 traffic go without trying to force it 443.

There are parts of this "force" issue, I think. One is, FreeIPA web application responds with redirects to ```https:``` to most ```http:``` requests, the other is that is does not make it possible to specify the port to be able to use something different than 443. Both are issues with FreeIPA server itself. In other words -- if this was not in container but say on a VM and you had to achieve the same, how would you do it?

Note that the issue is not new, it's actually tracked as https://fedorahosted.org/freeipa/ticket/3955.

> I think setting an ENV var would be good for this, but I may be wrong.

Environment variable might be nice mechanism but we need to know *what* to do with that.

It seems to me that the current best approach would be to just terminate the SSL on the host on the proxy (so that other locations on the host can be routed to other places), and use another https request to the container to reach the FreeIPA server.

Unless I'm missing something.

**Comment by joshuacox** [comment]
Ok, I'll give it a shot setting nginx up as man in the middle.  But for some reason, I was thinking that would not work as it would be detected as a man in the middle attack?  I'll experiment some more with this, and post back a solution if I can verify something.  And the 3955 ticket was very illuminating!  That not only could be a suitable solution to me (alternate ports), but it also illuminates how many occurrences of 443 and 80 there are everywhere, I had been foiled a couple of times by these already.

**Comment by joshuacox** [comment]
I'm giving in and letting FreeIPA have the ports, so I'm building another VM not octohost related especially for the FreeIPA instance.  I'm starting with something very simple:
https://github.com/joshuacox/dacksible
but if anyone is using a FreeIPA docker instance in one of the docker related projects, deis, flynn, dokku, or anything else I'd love to hear about it.  Eventually I'd like to work some sort of automated clustering mechanism.  Please contact me if any of this interests you, closing this issue.
