### ISSUE TITLE
Docker run fails with FreeIPA server configuration failed

### ISSUE THREAD

**Issue by olimination** [adelton/docker-freeipa#20]
I have prepared a freeipa data directory with a ipa-server-install-options file with the password properties as documented here: https://registry.hub.docker.com/u/adelton/freeipa-server/

But if I try to run the following Docker command:

```
sudo docker run --name freeipa-server-container -h ipa.example.test -v /home/my/programs/freeipa/data/:/data -ti adelton/freeipa-server:centos-7
```
I receive following error output:

_Usage: ipa-server-install [options]
ipa-server-install: error: In unattended mode you need to provide at least -r, -p and -a options
FreeIPA server configuration failed._

Do I miss something?

Thanks for help

**Comment by adelton** [comment]
Is it possible that you have spaces or other characters in your passwords in ```ipa-server-install-options```, making the ```ipa-server-install``` command line confused?

**Comment by olimination** [comment]
so far nope, I have the following in the file:

```
--ds-password=test12345
--admin-password=test12345
```

as documented in the README. 

But when I run it without this ipa-server-install-options file and set the password by passing the "-e" parameter to docker it worked:

```
sudo docker run --name freeipa-server-container -h ipa.example.test -v /home/my/programs/freeipa/data/:/data -e PASSWORD=Secret123 -ti adelton/freeipa-server:centos-7
```

**Comment by adelton** [comment]
I'm out of ideas. You might want to ```git clone``` the source repository, add some ```set -x``` and debugging and build your own image, to see why things are not passed to ```ipa-server-install``` like we expect it to be passed.

**Comment by olimination** [comment]
ok, I will try to check. For the moment I it also works with setting the "-e" for Docker.
Thanks.
