### ISSUE TITLE
httpd package error on unpacking

### ISSUE THREAD

**Issue by joshuacox** [adelton/docker-freeipa#22]
I'm getting problems with httpd in multiple branches (fedora21 as well as the centos-7 shown here), anyone else running into this, looking up into the install log it was here that it failed:
`Installing : httpd-2.4.6-31.el7.centos.x86_64                         200/373Error unpacking rpm package httpd-2.4.6-31.el7.centos.x86_64 `

**Comment by adelton** [comment]
What OS and docker versions do you use on the host? If you create Dockerfile with just
```
FROM <the-os>
RUN yum install -y httpd
```
and run ```docker build .```, does it pass?

**Comment by joshuacox** [comment]
I get the same thing, here's the requested info, and some more output:

```
$ uname -a
Linux mktulu.thalhalla.net 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
```
```
$ docker version
docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
```
mkdir /tmp/test
cd /tmp/test
echo FROM fedora:21>Dockerfile
echo RUN yum install -y httpd>>Dockerfile
docker  build .
```

Here's the output:
http://sprunge.us/ISNY

**Comment by adelton** [comment]
> Here's the output:
> http://sprunge.us/ISNY

So the relevant bits are:

```
Sending build context to Docker daemon
FATA[0000] Post http:///var/run/docker.sock/v1.18/build?cpusetcpus=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
thoth@mktulu:/tmp/test$ docker build .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon
Step 0 : FROM fedora:21
 ---> e26efd418c48
Step 1 : RUN yum install -y httpd
[...]
  Installing : httpd-2.4.10-15.fc21.x86_64                                  7/7Error unpacking rpm package httpd-2.4.10-15.fc21.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec;55636724: cpio: cap_set_file
```

You seem to be hitting https://github.com/docker/docker/issues/5928 and https://github.com/docker/docker/pull/5930. Can you please talk to your distribution's docker package maintainer about why docker on that platform does seem to still drop cap_set_file?

**Comment by joshuacox** [comment]
actually I'm using the latest docker binary straight from docker.  So no package maintainer, pretty much this:
```
wget https://get.docker.com/builds/Linux/x86_64/docker-latest
chmod +x docker-latest
sudo mv docker-latest /usr/local/bin/docker
```
is how I install Docker on Debian Jessie at the moment.

**Comment by joshuacox** [comment]
I went ahead and tried this on a ubuntu trusty host (3.16.0-38-generic #52~14.04.1-Ubuntu SMP) as well, Docker was built using the angstwad ansible role, I have a packer builder here:
https://github.com/joshuacox/dacksible
that was used to build the VM
I get the same errors as I did in debian.  Docker looks to be the same version there:
```
docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by joshuacox** [comment]
building on docker hub is a workaround for the moment

https://registry.hub.docker.com/u/joshuacox/docker-freeipa/

 though I'm tempted to fool around with AUFS or perhaps arch or gentoo as my host so I can grab a cutting edge version.  Maybe even BTRFS.

**Comment by adelton** [comment]
Thanks for the investigation. I'm closing this issue now.
