### ISSUE TITLE
Error unpacking rmp package

### ISSUE THREAD

**Issue by cedrick00** [adelton/docker-freeipa#23]
Im getting an error in installing this package
Installing : httpd-2.4.6-31.el7.centos.x86_64     73/83Error unpacking rpm package httpd-2.4.6-31.el7.centos.x86_64

**Comment by adelton** [comment]
We have been looking at the issue in https://github.com/adelton/docker-freeipa/issues/22 and it seems the docker daemon misbehaves. You might try different storage or different host OS/package.

**Comment by joshuacox** [comment]
I can recommend trying out the overlay storage driver, I've tried it and BTRFS and both solved numerous issues I was having.  Overlay does seem to be the more popular choice of the moment, I have both running in different VMs without issue, the AUFS continues to be plagued by growing problems.
