### ISSUE TITLE
Read-only file system errors running current docker image tags centos-7, latest

### ISSUE THREAD

**Issue by dmcnaught** [adelton/docker-freeipa#25]
Read-only file system errors running current docker image tags centos-7, latest

Tested on CoreOS, OSX-boot2docker, and nkinder tested on centos-7 on fedora (#freeipa chat)

Here is the command and output: http://www.codeshare.io/34wmc

Top snippet: 
core-01 ~ # docker run --name freeipa-server-container -ti    -h ipa.example.test    -v /var/lib/ipa-data:/data:Z adelton/freeipa-server:centos-7
tar: ./var/log/samba/old: Cannot utime: Read-only file system
tar: ./var/log/samba/old: Cannot change ownership to uid 0, gid 0: Read-only file system
tar: ./var/log/samba: Cannot utime: Read-only file system
....

**Comment by adelton** [comment]
I get NXDOMAIN about that www.codeshare.io.

I was not able to reproduce on Fedora 21.

**Comment by dmcnaught** [comment]
Strange - the codeshare link still works for me.
Running without the Z: seemed to get me further this morning. (Log start below)
Thanks

core-01 ~ # docker run --name freeipa-server-container -ti    -h ipa.example.test    -v /var/lib/ipa-data:/data adelton/freeipa-server:centos-7

The log file for this installation can be found in /var/log/ipaserver-install.log
==============================================================================
This program will set up the IPA Server.
...
