### ISSUE TITLE
ipa server can not be restarted

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#29]
**Overview**: When I create the container using docker run, it works well the first time (when there is no prior data volume). Then I get to a bash terminal, then I exit.

At this point I can not restart the freeipa container, either by running docker start, or by running the exact same docker run command used to create the container.
The reason seems to be that it can not resolve the freeipa hostname (ipa.quartzbio.com), which is expected because it is only defined in the docker host /etc/hosts, and the reason why I used 
**-h ipa.quartzbio.com and -e IPA_SERVER_IP=10.9.70.3**.

I don't know what to do, since I intend to use the DNS service provided by the freeipa container to resolve the hostname.

N.B: If I delete the data volume, I can run the docker without error.

```
docker run --name freeipa -ti \
	-e IPA_SERVER_IP=10.9.70.3 \
	-e IPA_SERVER_INSTALL_OPTS="--no-host-dns -d" \
	-h ipa.quartzbio.com \
	-e PASSWORD=$IPA_PASSWORD \
	-v /secure/freeipa_server/freeipa/data:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-p 53:53  -p 53:53/udp \
	-p 9980:80 -p 9943:443 \
	-p 389:389 -p 636:636 -p 88:88 -p 464:464 \
	-p 88:88/udp -p 464:464/udp -p 7389:7389 \
	-p 9443:9443 -p 9444:9444 -p 9445:9445  adelton/freeipa-server
FreeIPA server is already configured, starting the services.
Starting [ntpd.service]
Starting [certmonger.service]
Starting [ipa-dnskeysyncd.service]
Starting [fedora-domainname.service]
domainname: you must be root to change the domain name
Starting [ipa.service]
Starting Directory Service
Starting krb5kdc Service
Starting kadmin Service
Starting named Service
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 0.in-addr.arpa/IN: loaded serial 0
Starting ipa_memcached Service
Starting httpd Service
Starting pki-tomcatd Service
Starting ipa-otpd Service
Starting ipa-dnskeysyncd Service
ipa: INFO: The ipactl command was successful
Starting [sssd.service]
Host ipa.quartzbio.com not found: 3(NXDOMAIN)
Stopping ipa-dnskeysyncd Service
Stopping ipa-otpd Service
Stopping pki-tomcatd Service
```

**Comment by adelton** [comment]
> Overview: When I create the container using docker run, it works well the first time (when there is no prior data volume). Then I get to a bash terminal, then I exit.
> 

During that first `docker run`, while in that bash terminal (or get another one using `docker exec -ti freeipa bash`), what does `dig @127.0.01 ipa.quartzbio.com` and `dig @10.9.70.3 ipa.quartzbio.com` return?

> The reason seems to be that it can not resolve the freeipa hostname (ipa.quartzbio.com), which is expected because it is only defined in the docker host /etc/hosts, and the reason why I used
> -h ipa.quartzbio.com and -e IPA_SERVER_IP=10.9.70.3.

Whose IP addres is that 10.9.70.3?

> I don't know what to do, since I intend to use the DNS service provided by the freeipa container to resolve the hostname.

>    -e IPA_SERVER_INSTALL_OPTS="--no-host-dns -d" \

Why that `--no-host-dns`? That shouldn't be needed at all.

Related to https://github.com/adelton/docker-freeipa/issues/30: can you clarify what DNS servers (other than the one being setup in the FreeIPA container) you have running?

**Comment by kforner** [comment]
initial docker run:
```
dig @127.0.01 ipa.quartzbio.com
; <<>> DiG 9.9.6-P1-RedHat-9.9.6-8.P1.fc21 <<>> @127.0.01 ipa.quartzbio.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20070
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ipa.quartzbio.com.		IN	A

;; ANSWER SECTION:
ipa.quartzbio.com.	180	IN	A	10.9.70.3

;; AUTHORITY SECTION:
quartzbio.com.		86400	IN	NS	ipa.quartzbio.com.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jul 08 13:
```

```
dig @10.9.70.3 ipa.quartzbio.com
;; reply from unexpected source: 172.17.42.1#53, expected 10.9.70.3#53
;; reply from unexpected source: 172.17.42.1#53, expected 10.9.70.3#53
;; reply from unexpected source: 172.17.42.1#53, expected 10.9.70.3#53

; <<>> DiG 9.9.6-P1-RedHat-9.9.6-8.P1.fc21 <<>> @10.9.70.3 ipa.quartzbio.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

> Whose IP addres is that 10.9.70.3?

the docker host

> Why that --no-host-dns? That shouldn't be needed at all.

just an attempt to solve the problem, the option sounded nice ;)

> Related to #30: can you clarify what DNS servers (other than the one being setup in the FreeIPA container) you have running?

only the freeIPA DNS from your docker, but bound/forwarded to the docker host

**Comment by adelton** [comment]
If you use `-h ipa.quartzbio.com` to `docker run`, both to the initial and subsequent when the `/secure/freeipa_server/freeipa/data` is already populated, IPA in the container will be able to resolve itself because docker will put the correct record to `/etc/hosts`. The `dig` output shows that you really do not want to force (via various means) IPA to use the 10.9.70.3 internally for DNS lookups because it will not be happy when replies will arrive from its own internal 172.17.* range instead of host's IP address. Just let the container internally use 127.0.0.1.

The `-e IPA_SERVER_IP=10.9.70.3` is really only needed for outside clients, to put correct A record in for `ipa.quartzbio.com`.

> just an attempt to solve the problem, the option sounded nice ;)

Interesting. I never had to use it.
