### ISSUE TITLE
can not docker exec inside freeipa-server

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#31]
I do not know if it is related to the freeipa-server container, or a problem with my docker installation, but I can not connect inside the running server:
```
docker exec -ti freeipa bash
Cannot run exec command e67d75c75f8b082b104267d3bbb0fb2d95e341ecdc33e7faf612807b9fa32077 in container 926ef3ee2b0b6bbdc27f1875b006c4dcabf040558fb8d8063d723c297643e110: write parent: broken pipe
                                   Error starting exec command in container e67d75c75f8b082b104267d3bbb0fb2d95e341ecdc33e7faf612807b9fa32077: Cannot run exec command e67d75c75f8b082b104267d3bbb0fb2d95e341ecdc33e7faf612807b9fa32077 in container 926ef3ee2b0b6bbdc27f1875b006c4dcabf040558fb8d8063d723c297643e110: write parent: broken pipe
```

One of my use case is to reload the name service (rndc reload).

P.S
I hope I'not creating too many issues...

**Comment by dmcnaught** [comment]
use /bin/bash instead of bash

**Comment by adelton** [comment]
Is it possible that this is on Fedora 22 and you are hitting SELinux issue https://bugzilla.redhat.com/show_bug.cgi?id=1232803 ?

**Comment by kforner** [comment]
The problem was general, due to a kernel < 3.8. You can close the issue, sorry for the false positive.
