### ISSUE TITLE
centos-7 replica container entrypoint fails:

### ISSUE THREAD

**Issue by dmcnaught** [adelton/docker-freeipa#33]
Command:
$ docker run -ti --name freeipa-replica-container -h ipareplica1.developnet.io -v /var/lib/ipa-data:/data -e IPA_SERVER_IP=ip-here -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp -p 7389:7389 -p 9443:9443 -p 9444:9444 -p 9445:9445 adelton/freeipa-server:centos-7
Usage: ipa-replica-install [options] REPLICA_FILE

ipa-replica-install: error: you must provide a file generated by ipa-replica-prepare
FreeIPA server configuration failed.

Then if I run the command that I think throws the error:
[root@ip-172-31-27-104 /]# /usr/sbin/ipa-replica-install /data/*.gpg
Directory Manager (existing master) password:

Run connection check to master
...
it works - but it does prompt me for the passwords, even though they are in ipa-replica-install-options
[root@ip-172-31-27-104 /]# cat /data/ipa-replica-install-options
\# This file was written by cloud-config.
--password=password1
--admin-password=password1

**Comment by adelton** [comment]
> ipa-replica-install: error: you must provide a file generated by ipa-replica-prepare
> FreeIPA server configuration failed.

Just place the `*.gpg` file to `/var/lib/ipa-data` before you run the container.

> but it does prompt me for the passwords, even though they are in ipa-replica-install-options

The `ipa-replica-install-options` is only processed during the initial setup, not when you run the `ipa-replica-install` manually.

Also I'm not sure if the comment line in the `/data/ipa-replica-install-options` doesn't cause the rest of the options to be ignored -- we don't support comments there.

**Comment by dmcnaught** [comment]
Thanks @adelton it must have been the comment in the options file as when I removed it, it found the gpg file. That wasn't a problem with the first server.
