### ISSUE TITLE
Issue with working with OTP 

### ISSUE THREAD

**Issue by coolacid** [adelton/docker-freeipa#34]
There seems to be major issues when implementing OTP. First problem is the systemd file :: /usr/lib/systemd/system/ipa-otpd@.service --the enviromentfile this is pointing at /etc/ipa/default.conf. This breaks when the systemd attempts to add the  [global] tag.

Attempted to patch that and point to the same file without the [global] tag however all OTP still fails with no real indication as to why.

**Comment by coolacid** [comment]
The initial problem appears to have been because latest was mapped to :21 tag. Forcing :22 seems to have allowed the service to start. 

OTP is still not working (it appears)

**Comment by adelton** [comment]
> There seems to be major issues when implementing OTP. First problem is the systemd file :: /usr/lib/systemd/system/ipa-otpd@.service --the enviromentfile this is pointing at /etc/ipa/default.conf. This breaks when the systemd attempts to add the [global] tag.

In the FreeIPA container, no systemd is running. Could you please be more specific about the functional issue?

**Comment by coolacid** [comment]
This is related to using the One Time Password function. Removing the [global] tag (or pointing the @.service file directly to the ldap server) causes the otp service to start - so something is allowing it to run. 

Because we couldn't get IPA with OTP working within Docker, we had to scrap and go bare metal, so can't look into it any further.

**Comment by dmcnaught** [comment]
I'm seeing the same issue trying to use OTP-TOTP. Set up all goes fine in the GUI, but then when I try to login after successfully syncing OTP token, I see this in the logs:
==> /var/log/krb5kdc.log <==
Jul 22 21:47:01 ip-172-31-28-101.ec2.internal krb5kdc[2035](info): AS_REQ (6 etypes {18 17 16 23 25 26}) 172.17.0.16: NEEDED_PREAUTH: tuser@EC2.INTERNAL for krbtgt/EC2.INTERNAL@EC2.INTERNAL, Additional pre-authentication required
Jul 22 21:47:01 ip-172-31-28-101.ec2.internal krb5kdc[2035](info): closing down fd 12
==> /var/log/systemctl.log <==
[start ipa-otpd@.service]
Running [export host=ip-172-31-28-101.ec2.internal; export basedn=dc=ec2,dc=internal; export realm=EC2.INTERNAL; export domain=ec2.internal; export xmlrpc_uri=https://ip-172-31-28-101.ec2.internal/ipa/xml; export ldap_uri=ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket; export enable_ra=True; export ra_plugin=dogtag; export dogtag_version=10; export mode=production; /usr/libexec/ipa-otpd $ldap_uri]
Marked pid [2913] for [ipa-otpd@.service]
LDAP: ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket
Socket closed, shutting down...
[start ipa-otpd@.service]
Running [export host=ip-172-31-28-101.ec2.internal; export basedn=dc=ec2,dc=internal; export realm=EC2.INTERNAL; export domain=ec2.internal; export xmlrpc_uri=https://ip-172-31-28-101.ec2.internal/ipa/xml; export ldap_uri=ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket; export enable_ra=True; export ra_plugin=dogtag; export dogtag_version=10; export mode=production; /usr/libexec/ipa-otpd $ldap_uri]
Marked pid [2916] for [ipa-otpd@.service]
LDAP: ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket
Socket closed, shutting down...
[start ipa-otpd@.service]
Running [export host=ip-172-31-28-101.ec2.internal; export basedn=dc=ec2,dc=internal; export realm=EC2.INTERNAL; export domain=ec2.internal; export xmlrpc_uri=https://ip-172-31-28-101.ec2.internal/ipa/xml; export ldap_uri=ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket; export enable_ra=True; export ra_plugin=dogtag; export dogtag_version=10; export mode=production; /usr/libexec/ipa-otpd $ldap_uri]
Marked pid [2919] for [ipa-otpd@.service]
LDAP: ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket
Socket closed, shutting down...
[start ipa-otpd@.service]
Running [export host=ip-172-31-28-101.ec2.internal; export basedn=dc=ec2,dc=internal; export realm=EC2.INTERNAL; export domain=ec2.internal; export xmlrpc_uri=https://ip-172-31-28-101.ec2.internal/ipa/xml; export ldap_uri=ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket; export enable_ra=True; export ra_plugin=dogtag; export dogtag_version=10; export mode=production; /usr/libexec/ipa-otpd $ldap_uri]
Marked pid [2922] for [ipa-otpd@.service]
LDAP: ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket
Socket closed, shutting down...

==> /var/log/krb5kdc.log <==
Jul 22 21:47:07 ip-172-31-28-101.ec2.internal krb5kdc[2036](info): preauth (otp) verify failure: Connection timed out
Jul 22 21:47:07 ip-172-31-28-101.ec2.internal krb5kdc[2036](info): AS_REQ (6 etypes {18 17 16 23 25 26}) 172.17.0.16: PREAUTH_FAILED: tuser@EC2.INTERNAL for krbtgt/EC2.INTERNAL@EC2.INTERNAL, Preauthentication failed
Jul 22 21:47:07 ip-172-31-28-101.ec2.internal krb5kdc[2036](info): closing down fd 12

**Comment by dmcnaught** [comment]
I also commented out the first line in /data/etc/ipa/default.conf
otherwise this was the log output:
[start ipa-otpd@.service]
Running [export [global]; export host=ip-172-31-28-101.ec2.internal; export basedn=dc=ec2,dc=internal; export realm=EC2.INTERNAL; export domain=ec2.internal; export xmlrpc_uri=https://ip-172-31-28-101.ec2.internal/ipa/xml; export ldap_uri=ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket; export enable_ra=True; export ra_plugin=dogtag; export dogtag_version=10; export mode=production; /usr/libexec/ipa-otpd $ldap_uri]
Marked pid [2826] for [ipa-otpd@.service]
sh: line 0: export: `[global]': not a valid identifier
LDAP: ldapi://%2fvar%2frun%2fslapd-EC2-INTERNAL.socket
Socket closed, shutting down...

**Comment by dmcnaught** [comment]
Some more info: When I use google  authenticator I get this error message when adding the token. (centos-7 and fedora-22). Authy allows me to add the token.
![img_3250](https://cloud.githubusercontent.com/assets/5974394/8864161/113dbc12-315c-11e5-806d-1ea7b992d304.jpg)

**Comment by dmcnaught** [comment]
Also tried adding the token with FreeOTP - can't login to the admin tools with password+token after setup.

**Comment by npmccallum** [comment]
@dmcnaught The "invalid barcode" issue is related to this bug: https://www.redhat.com/archives/freeipa-devel/2015-June/msg00505.html

**Comment by dmcnaught** [comment]
Notes from mailing list:
@adelton : Can we run systemd in the centos-7 container so that ipa-otp will work?

>On Mon, 2015-09-21 at 16:49 -0600, Duncan McNaught wrote:
>> Dear freeipa-users,
>>
>> I'm having an issue with otp in freeipa. I can set up the service as
>> described in the blog post for TOTP or HOTP, and sync the token fine.
>> When I try to login to the admin tools or an ipa-managed client
>> (with <password><token>) , I get a password incorrect message.
>> Here are some more details: https://github.com/adelton/docker-freeipa
>> /issues/34
>> Can anyone help me to debug/get this working?
>
>I'm very unclear as to what you are trying to do. Are you trying to
>run FreeIPA in a container? If so, Jan is probably your man. AFAIK,
>ipa-otpd will require systemd in the container.
>
>If you are trying to run this on CentOS 7.1 (not a container), it
>seems to me that your LDAP server isn't running or something is wrong
>with ldapi.
>
>Can you explain your setup in more detail?

**Comment by adelton** [comment]
> Notes from mailing list:
> @adelton : Can we run systemd in the centos-7 container so that ipa-otp will work?

Not yet, it should be possible with Docker 1.9.

**Comment by adelton** [comment]
Fix for the issue was now pushed to the master branch and also to the rhel-7 and centos-7 branches. The automated builds on the hub are running and updated images should be available shortly.

Sorry it took me so long to resolve the problem.

**Comment by dmcnaught** [comment]
Great - thanks @adelton
