### ISSUE TITLE
Implement full grsec support?

### ISSUE THREAD

**Issue by ninja-** [adelton/docker-freeipa#36]
```
grsec: use of CAP_SETFCAP in chroot denied for /usr/bin/docker[exe:22977] uid/euid:0/0 gid/egid:0/0, parent /usr/bin/docker[docker:21162] uid/euid:0/0 gid/egid:0/0
```

sadly...
is there a way for the container to work without the caps?
what's the reasoning behind "--cap-add=SYS_TIME"?

**Comment by ninja-** [comment]
nevermind
```
sysctl kernel.grsecurity.chroot_caps=0
```

**Comment by ninja-** [comment]
but...this needs to have pax flags on java and maybe other processes to work. Similar to what I added to docker-gitlab.

**Comment by adelton** [comment]
> what's the reasoning behind "--cap-add=SYS_TIME"?

If you are running ntpd in that container, you need this capability.

**Comment by adelton** [comment]
> but...this needs to have pax flags on java and maybe other processes to work. Similar to what I added to docker-gitlab.

Could you please elaborate what you do and what seems to be the issue? What branch, what OS, what docker (package) version?

What chroot is this about?

**Comment by ninja-** [comment]
yes @adelton I made a Dockerfile patch that downloads paxctl and adds a flag to java so it won't crash

**Comment by ninja-** [comment]
```
FROM fedora:22

MAINTAINER Jan Pazdziora

# Install FreeIPA server
RUN mkdir -p /run/lock ; dnf install -y freeipa-server bind bind-dyndb-ldap perl && dnf clean all
RUN wget 'http://copr-be.cloud.fedoraproject.org/results/tommyj/grsecurity/fedora-19-x86_64/paxctl-0.9-1.fc20/paxctl-0.9-1.fc19.x86_64.rpm' -O /tmp/grsec.rpm \
&& dnf install -y /tmp/grsec.rpm && rm -rf /tmp/grsec.rpm

ADD dbus.service /etc/systemd/system/dbus.service
RUN ln -sf dbus.service /etc/systemd/system/messagebus.service
ADD httpd.service /etc/systemd/system/httpd.service

ADD systemctl /usr/bin/systemctl
ADD systemctl-socket-daemon /usr/bin/systemctl-socket-daemon

ADD ipa-server-configure-first /usr/sbin/ipa-server-configure-first

RUN chmod -v +x /usr/bin/systemctl /usr/bin/systemctl-socket-daemon /usr/sbin/ipa-server-configure-first

RUN groupadd -g 389 dirsrv ; useradd -u 389 -g 389 -c 'DS System User' -d '/var/lib/dirsrv' --no-create-home -s '/sbin/nologin' dirsrv

ADD volume-data-list /etc/volume-data-list
ADD volume-data-mv-list /etc/volume-data-mv-list
RUN set -e ; cd / ; mkdir /data-template ; cat /etc/volume-data-list | while read i ; do echo $i ; if [ -e $i ] ; then tar cf - .$i | ( cd /data-template && tar xf - ) ; fi ; mkdir -p $( dirname $i ) ; if [ "$i" == /var/log/ ] ; then mv /var/log /var/log-removed ; else rm -rf $i ; fi ; ln -sf /data${i%/} ${i%/} ; done
ADD volume-data-autoupdate /etc/volume-data-autoupdate
RUN rm -rf /var/log-removed
RUN mv /data-template/etc/dirsrv/schema /usr/share/dirsrv/schema && ln -s /usr/share/dirsrv/schema /data-template/etc/dirsrv/schema
RUN echo 0.5 > /etc/volume-version
RUN uuidgen > /data-template/build-id

RUN paxctl -cm /usr/lib/jvm/jre/bin/java

EXPOSE 53/udp 53 80 443 389 636 88 464 88/udp 464/udp 123/udp 7389 9443 9444 9445

VOLUME /data

ENTRYPOINT /usr/sbin/ipa-server-configure-first
```

**Comment by adelton** [comment]
> I made a Dockerfile patch that downloads paxctl and adds a flag to java so it won't crash. very happy with the result!

What is the general situation with grsecurity with docker with capabilities? Why is that paxctl a good thing?

**Comment by ninja-** [comment]
@adelton so there is a list of exceptions to grsec's memory protection and java is one of them since it does some runtime magic. it's listed in grsec configuration, but that wouldn't work in container. so the memory protection needs to be manually disabled on java with a flag

**Comment by adelton** [comment]
Does the memory protection need to be disabled only in the container case, or for setup on the host as well? Shouldn't the ```paxctl``` be part of rpm installation in general?

**Comment by ninja-** [comment]
@adelton for installation "on host" paxctl config would fix java automatically but that doesn't work with containers since path is different

**Comment by adelton** [comment]
Automatically, meaning via rpm triggers? That should work in containers as well.

I believe the same mechanism should be used in the base images if containers under grsecurity are to be reasonably supported. I don't like the idea of every container that uses java having to fetch an extra package from copr and running the ```paxctl``` manually. Therefore closing this issue now -- please raise this with the base images.
