### ISSUE TITLE
Unknown operation 'start-enabled' and 'stop-running' after dnf upgrade and docker restart.

### ISSUE THREAD

**Issue by vDorst** [adelton/docker-freeipa#41]
docker start -ia ipa
```
"/var/log" already exists and is not a directory.
FreeIPA server is already configured, starting the services.
Unknown operation 'start-enabled'.
Unknown operation 'stop-running'.
```

**Comment by vDorst** [comment]
At this point is goes wrong https://github.com/adelton/docker-freeipa/blob/master/ipa-server-configure-first#L135

**Comment by adelton** [comment]
Can you exec bash in the container and check ```systemctl```? We overwrite the ```/usr/bin/systemctl``` with a script that should understand those directives ...

**Comment by vDorst** [comment]
replacing the scripts again solved the problem.
