### ISSUE TITLE
ENTRYPOINT script fails on first start

### ISSUE THREAD

**Issue by slobodyanyuk** [adelton/docker-freeipa#42]
Script **/usr/sbin/ipa-server-configure-first**

fails with:

>[root@ipa data]# systemd-tmpfiles --remove --create
>[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to replace specifiers: /var/log/journal/%m
>[/usr/lib/tmpfiles.d/systemd.conf:26] Failed to replace specifiers: /run/log/journal/%m
>[/usr/lib/tmpfiles.d/systemd.conf:28] Failed to replace specifiers: /run/log/journal/%m
>[/usr/lib/tmpfiles.d/systemd.conf:29] Failed to replace specifiers: /run/log/journal/%m
>[/usr/lib/tmpfiles.d/systemd.conf:32] Failed to replace specifiers: /var/log/journal/%m
>[/usr/lib/tmpfiles.d/systemd.conf:34] Failed to replace specifiers: /var/log/journal/%m
>[/usr/lib/tmpfiles.d/systemd.conf:35] Failed to replace specifiers: /var/log/journal/%m
>"/var/log" already exists and is not a directory.

host image: **"docker.io/fedora    23"**

**Comment by adelton** [comment]
What is ```/var/log``` in your container? It should be a symlink to ```/data/var/log```.

**Comment by slobodyanyuk** [comment]
It is symlink. But  **systemd-tmpfiles** doesn't like it for some reason.
Container still works with this message from  **systemd-tmpfiles** but it would be great to fix it.

**Comment by adelton** [comment]
> Container still works with this message from systemd-tmpfiles but it would be great to fix it.

Fixed in master and fedora-23 branches in commit e699660e3f5e01d3c2203b16b1e15f4bb92ff2fa.

Thank you.

**Comment by slobodyanyuk** [comment]
Thank you too.
