### ISSUE TITLE
stopped services reported by ipactl status

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#45]
Sorry, yet another issue.

In my freeipa server docker, if I run ipactl status, I get:
```
# ipactl status
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
named Service: RUNNING
ipa_memcached Service: RUNNING
httpd Service: RUNNING
pki-tomcatd Service: STOPPED
ipa-otpd Service: STOPPED
ipa-dnskeysyncd Service: STOPPED
ipa: INFO: The ipactl command was successful
```

Is this normal ? 

Thanks

**Comment by adelton** [comment]
> Is this normal ?

I'd consider it an unfortunate side-effect of the systemctl emulation that we do in the container where we only cover some of the code paths.

I've just checked that in the master-systemd branch where the native systemctl/systemd is used, the output is correct:

```
# docker exec -ti freeipa-server-container ipactl status
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
named Service: RUNNING
ipa_memcached Service: RUNNING
httpd Service: RUNNING
pki-tomcatd Service: RUNNING
ipa-otpd Service: RUNNING
ipa-dnskeysyncd Service: RUNNING
ipa: INFO: The ipactl command was successful
```

If you could test that branch and provide feedback, it would help us boost confidence in this setup and merge it to the "standard" master.

**Comment by kforner** [comment]
>I'd consider it an unfortunate side-effect of the systemctl emulation that we do in the container where we >only cover some of the code paths.
So you mean that the output is incorrect, but that the services are probably ok ?

>If you could test that branch and provide feedback, it would help us boost confidence in this setup and >merge it to the "standard" master.
I'll try to test it.

**Comment by adelton** [comment]
> So you mean that the output is incorrect, but that the services are probably ok ?

Right.
