### ISSUE TITLE
How to: upgrade

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#48]
Say you have a working freeipa, using your docker, with a given freeipa version, e.g. 4.1, and a local mount using -v to /data
Now if I want to upgrade to the latest docker version, e.g. 4.2.3, or 4.3.
Is it enough to pull the newer docker, and to re-run it with the same docker command-line used to run the old one, with a mount to the same /data ?

**Comment by adelton** [comment]
Yes.

Having the data volume backed-up prior to that is certainly advisable.

**Comment by kforner** [comment]
thanks. It's maybe worth adding it to the README.
