### ISSUE TITLE
exec starting with -

### ISSUE THREAD

**Issue by muayyad-alsadi** [adelton/docker-freeipa#52]
I was looking in my logs and found this

```
Can't exec "-/usr/bin/kdestroy": No such file or directory at /bin/systemctl line 341.
```

**Comment by muayyad-alsadi** [comment]
I removed - from /usr/lib/systemd/system/httpd.service.d/abc.conf till we fix this

```
cat <<EOF >abc.conf 
[Service]
Environment=KRB5CCNAME=/var/run/httpd/ipa/krbcache/krb5ccache
Environment=KDCPROXY_CONFIG=/etc/ipa/kdcproxy/kdcproxy.conf
ExecStartPre=/usr/libexec/ipa/ipa-httpd-kdcproxy
ExecStopPost=/usr/bin/kdestroy -A
EOF
docker cp abc.conf ipa:/usr/lib/systemd/system/httpd.service.d/abc.conf
docker start ipa
```

**Comment by adelton** [comment]
> I was looking in my logs and found this

Which log was this and during which operation?

**Comment by muayyad-alsadi** [comment]
My specific case is irrelevant. Just look at the following file `/usr/lib/systemd/system/httpd.service.d/abc.conf` which says `ExecStopPost=-/usr/bin/kdestroy -A` and line 341 of `systemctl` perl script would execute `-/usr/bin/kdestroy -A` with extra minus. I sent you a patch the strip leading `-` from ExecStopPre and ExecStopPost.

Most likely it did not happen before because `abc.conf` did not have this -.

> Which log was this and during which operation?

the stdout/err by typing `docker logs --tail=20 -f my-ipa`
I believe the operation was normal start of stopped container during the boot.

Please accept my pull request.
