### ISSUE TITLE
systemctl should log to stdout/stderr

### ISSUE THREAD

**Issue by muayyad-alsadi** [adelton/docker-freeipa#54]
hi,

around line 600 I see the code below

```
	if ($pid == 0) {
		open(STDOUT, '>>', '/var/log/systemctl.log');
		open(STDERR, '>>', '/var/log/systemctl.log');
		open(STDIN, '<', '/dev/null');
		POSIX::setsid();
		exec "$ENV@paths";
	}
```

but it's good for containers to log to /dev/stderr and /dev/stdout instead of files
to avoid writing to containers files (overlayfs / device mapper)
and to allow logs to be collected later by host logging like `docker logs -f` and hosts `journald`

I can send pull request but I believe the fix is obvious.

**Comment by adelton** [comment]
The `/var/log` is a symlink to `/data/var/log` so the logs do not end up in overlayfs / devicemapper backends.

In the master-systemd branch we move to the native systemd/systemctl, so we will be able to have proper solution there. In the current master, I prefer to keep the logging the way it was from the beginning, not to disrupt people's existing setups.
