### ISSUE TITLE
latest error

### ISSUE THREAD

**Issue by santosh0705** [adelton/docker-freeipa#56]
I tried to build image today and getting below error:

`systemd 222 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <freeipa.locuz.com>.
Failed to install release agent, ignoring: No such file or directory
Failed to create root cgroup hierarchy: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.`

Same error with pulled Docker image.

Yesterday the build was working perfectly.

**Comment by adelton** [comment]
I assume this is in run-time, not build time.

Please note that with the latest changes in master, you need to use `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` with `docker run`.

**Comment by adelton** [comment]
I assume using the `-v` as shown above fixed the issue, closing now.
