### ISSUE TITLE
IPA_SERVER_IP does not appear to be sticking?

### ISSUE THREAD

**Issue by joshuacox** [adelton/docker-freeipa#58]
```
docker run --name=demofreeipa \
        -d \
        -e IPA_SERVER_IP=$(IPA_SERVER_IP) \
        -p 53:53/udp -p 53:53 \
        -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 \
        -p 88:88/udp -p 464:464/udp -p 123:123/udp -p 7389:7389 \
        -p 9443:9443 -p 9444:9444 -p 9445:9445 \
        -h demo.freeipa.example.com \
        -e PASSWORD=$(FREEIPA_MASTER_PASS) \
        -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
        -t adelton/freeipa-server:fedora-23
```

```
The IPA Master Server will be configured with:
Hostname:       demo.freeipa.example.com
IP address(es): 172.17.0.2
```
which is the docker IP address not the one I fed it previously with `-e IPA_SERVER_IP=$(IPA_SERVER_IP)`

for consistency sake I made a Makefile that prompts for anything specific to the installation (and gitignores all the responses so I don't commit my master password etc to git):

https://github.com/joshuacox/mkFreeIPA

it's intended use would be `make temp`, and it would make you a temporary freeIPA server quickly, that you could make persistent after you got it running with `make grab`, and then `make rmtemp`, and finally `make prod` to run the container with the persistent directories.  But alas, it fails on `make temp` with 

```
  [error] CalledProcessError: Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 1
ipa.ipapython.install.cli.install_tool(Server): ERROR    Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 1
FreeIPA server configuration failed.
```

which may or may not be related to the IP address not being passed correctly.

can you spot what I'm doing wrong?  I know I had this working a few months ago, and now something seems off, it's most likely me and I'd appreciate any extra eyes.

**Comment by adelton** [comment]
> The IPA Master Server will be configured with:
> Hostname:       demo.freeipa.example.com
> IP address(es): 172.17.0.2
> 
> which is the docker IP address not the one I fed it previously with -e IPA_SERVER_IP=$(IPA_SERVER_IP)

This is expected. We cannot pass the external IP address directly to `ipa-server-install` since it insists in checking if the IP address is local on the host / in the environment running the server. So it would fail in many Docker installations. See https://fedorahosted.org/freeipa/ticket/2648 for more details.

Instead, we let the `ipa-server-install` run with whatever IP address it finds in the container, and only after the server was configured and is up and running, we set the IP address for the IPA server hostname to the one provided with `IPA_SERVER_IPA`. So running

```
dig @127.0.0.1 demo.freeipa.example.com
```

on the host should output value of `$IPA_SERVER_IP`.

**Comment by adelton** [comment]
> But alas, it fails on make temp with
> 
>   [error] CalledProcessError: Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 1
> ipa.ipapython.install.cli.install_tool(Server): ERROR    Command ''/bin/systemctl' 'restart' 'httpd.service'' returned non-zero exit status 1
> FreeIPA server configuration failed.
> 
> which may or may not be related to the IP address not being passed correctly.

Should I venture a guess and if you are running this on Debian with AUFS, the `httpd` package did not install properly -- see https://github.com/adelton/docker-freeipa/issues/55.

**Comment by joshuacox** [comment]
on ubuntu 14.04 for that one, but I'm betting you are probably right with it being an AUFS issue, or related,  I think I'll just use centos7 instead for this particular application.   I appreciate you pointing me to #55
