### ISSUE TITLE
Fedora23 docker image in github is missing httpd

### ISSUE THREAD

**Issue by iconoeugen** [adelton/docker-freeipa#60]
The Fedora23 image built on `2016-03-09T15:28:08.344Z` is missing the httpd package. An error is logged in the build log [bhrim8ftzilufofvxquu4sj](https://hub.docker.com/r/adelton/freeipa-server/builds/bhrim8ftzilufofvxquu4sj/):

```
error: httpd-2.4.18-1.fc23.x86_64: install failed
```

Please rebuild the docker image for Fedora23 and upload to docker hub.

**Comment by adelton** [comment]
The Docker hub builders are broken with https://github.com/docker/docker/issues/6980. Ticket was files. My attempts to have a note to this affect in https://hub.docker.com/r/adelton/freeipa-server/ seem to get lost ... I've added the note there now.

Please build the image from sources.
