### ISSUE TITLE
Changelog would be super helpful

### ISSUE THREAD

**Issue by frol** [adelton/docker-freeipa#61]
Changelog or at the very least a notice in the README about backwards incompatible changes would be super helpful! I have spent 4 hours trying to upgrade my FreeIPA installation when I decided to check the commit logs and found out that `/sys/fs/cgroup` must be mounted due to Systemd changes.

For the purpose of search engine indexing, my container was just hanging with only one line in the logs:

> FreeIPA server is already configured but with different version, volume update.

**Comment by adelton** [comment]
I'm sorry about your experience.

My hope was that the check in https://github.com/adelton/docker-freeipa/blob/master/init-data#L24 would catch the situation and warn you about the `/sys/fs/cgroup` change. I do get

```
$ docker run fedora:23 ls -dZ /sys/fs/cgroup
system_u:object_r:svirt_sandbox_file_t:s0:c230,c523 /sys/fs/cgroup
$ docker run -v /sys/fs/cgroup:/sys/fs/cgroup:ro fedora:23 ls -dZ /sys/fs/cgroup
system_u:object_r:tmpfs_t:s0 /sys/fs/cgroup
```

What outputs on what versions of docker / OS do you get for the above commands?

**Comment by frol** [comment]
@adelton I'm using Ubuntu 14.04 server with Docker 1.10.3 and I have a docker-compose config for FreeIPA.

```
$ docker run fedora:23 ls -dZ /sys/fs/cgroup
? /sys/fs/cgroup

$ docker run -v /sys/fs/cgroup:/sys/fs/cgroup:ro fedora:23 ls -dZ /sys/fs/cgroup
? /sys/fs/cgroup
```

**Comment by adelton** [comment]
Ah, so you don't have SELinux enabled.

We'll have to figure out if there is some other way to detect the situation. Could you please show output of

```
$ docker run fedora:23 mount | grep /sys/fs/cgroup | head -1
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,context="system_u:object_r:svirt_sandbox_file_t:s0:c25,c90",mode=755)
$ docker run -v /sys/fs/cgroup:/sys/fs/cgroup:ro fedora:23 mount | grep /sys/fs/cgroup | head -1
tmpfs on /sys/fs/cgroup type tmpfs (ro,seclabel,mode=755)
```

?

**Comment by frol** [comment]
I think the upgrade didn't go well (due to some of my manual intrusion), could you please suggest how I can fix the following errors I find in `journalctl` output:

```
freeipa.host named-pkcs11[296]: configuring command channel from '/etc/rndc.key'
freeipa.host named-pkcs11[296]: open: /etc/rndc.key: permission denied
freeipa.host named-pkcs11[296]: couldn't add command channel 127.0.0.1#953: permission denied
freeipa.host named-pkcs11[296]: configuring command channel from '/etc/rndc.key'
freeipa.host named-pkcs11[296]: open: /etc/rndc.key: permission denied
freeipa.host named-pkcs11[296]: couldn't add command channel ::1#953: permission denied
```

```
freeipa.host pkidaemon[370]: WARNING:  Symbolic link '/var/lib/pki/pki-tomcat/ca/logs' does NOT exist!
freeipa.host pkidaemon[370]: INFO:  Attempting to create '/var/lib/pki/pki-tomcat/ca/logs' -> '/var/log/pki/pki-tomcat/ca' . . .
freeipa.host pkidaemon[370]: ERROR:  Failed making '/var/lib/pki/pki-tomcat/ca/logs' -> '/var/log/pki/pki-tomcat/ca' since target '/var/log/pki/pki-tomcat/ca' does NOT exist!
```

```
freeipa.host ipa-dnskeysyncd[549]: ipa: WARNING: session memcached servers not running
freeipa.host ipa-dnskeysyncd[549]: ipa         : CRITICAL Kerberos authentication failed: (13, 'Permission denied')
```

P.S. At least Web UI, DNS, LDAP are working just fine, but still those errors are a bit scary.

**Comment by frol** [comment]
Yeah, I don't have SELinux enabled.

Here is the requested output:

```
$ docker run fedora:23 mount | grep /sys/fs/cgroup | head -1
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)

$ docker run -v /sys/fs/cgroup:/sys/fs/cgroup:ro fedora:23 mount | grep /sys/fs/cgroup | head -1
none on /sys/fs/cgroup type tmpfs (ro,relatime,size=4k,mode=755)
```

Why don't just check for `/sys/fs/cgroup` emptiness?

**Comment by adelton** [comment]
> Why don't just check for /sys/fs/cgroup emptiness?

Is /sys/fs/cgroups empty on your system?

```
$ docker run fedora:23 ls -la /sys/fs/cgroup
```

**Comment by frol** [comment]
Ooops, I assumed so, but it was a wrong assumption. Sorry for that.

**Comment by adelton** [comment]
> freeipa.host named-pkcs11[296]: configuring command channel from '/etc/rndc.key'
> freeipa.host named-pkcs11[296]: open: /etc/rndc.key: permission denied

On my installation, I have

```
# ls -lad /etc/rndc.key /data/etc/rndc.key
-rw-r-----. 1 root named 77 Mar 17 14:03 /data/etc/rndc.key
lrwxrwxrwx. 1 root root  18 Mar 17 13:55 /etc/rndc.key -> /data/etc/rndc.key
```

> freeipa.host pkidaemon[370]: WARNING:  Symbolic link '/var/lib/pki/pki-tomcat/ca/logs' does NOT exist!
> freeipa.host pkidaemon[370]: INFO:  Attempting to create '/var/lib/pki/pki-tomcat/ca/logs' -> '/var/log/pki/pki-tomcat/ca' . . .
> freeipa.host pkidaemon[370]: ERROR:  Failed making '/var/lib/pki/pki-tomcat/ca/logs' -> '/var/log/

```
# ls -lad /var/lib/pki /var/lib/pki/pki-tomcat/ca/logs
lrwxrwxrwx. 1 root    root    17 Mar 17 13:55 /var/lib/pki -> /data/var/lib/pki
lrwxrwxrwx. 1 pkiuser pkiuser 26 Mar 17 13:58 /var/lib/pki/pki-tomcat/ca/logs -> /var/log/pki/pki-tomcat/ca
```

**Comment by frol** [comment]
Thank you for providing `ls` outputs! I recovered the permissions and now I have only the last error left:

```
freeipa.host ipa-dnskeysyncd[916]: ipa: WARNING: session memcached servers not running
freeipa.host ipa-dnskeysyncd[916]: ipa         : DEBUG    Kerberos principal: ipa-dnskeysyncd/freeipa.sparky.salford-systems.com
freeipa.host ipa-dnskeysyncd[916]: ipa         : DEBUG    Initializing principal ipa-dnskeysyncd/freeipa.sparky.salford-systems.com using keytab /etc/ipa/dnssec/ipa-dnskeysyncd.keytab
freeipa.host ipa-dnskeysyncd[916]: ipa         : DEBUG    using ccache /tmp/ipa-dnskeysyncd.ccache
freeipa.host ipa-dnskeysyncd[916]: ipa         : CRITICAL Kerberos authentication failed: (13, 'Permission denied')
```

The warning is also rather strange since I can see memcached running:

```
$ ps ax | grep memcached
  353 ?        Ssl    0:00 /usr/bin/memcached -d -s /var/run/ipa_memcached/ipa_memcached -u apache -m 64 -c 1024 -P /var/run/ipa_memcached/ipa_memcached.pid
```

**Comment by adelton** [comment]
```
# ls -la /tmp/ipa-dnskeysyncd.ccache /var/run/ipa_memcached/ipa_memcached
-rw-------. 1 ods    named  1759 Mar 17 10:02 /tmp/ipa-dnskeysyncd.ccache
srwx------. 1 apache apache    0 Mar 17 10:02 /var/run/ipa_memcached/ipa_memcached
```

Not sure if any of these are the cause though.

**Comment by frol** [comment]
Those files have the same permissions on my end. It seems that I will need to add more debug output to the `/usr/libexec/ipa/ipa-dnskeysyncd` Python script.

**Comment by frol** [comment]
@adelton Could you please take a look what permissions are for: `/etc/ipa/dnssec/ipa-dnskeysyncd.keytab`? I had `memcached:cgred`, but once I have changed to `memcached:named`, `ipa-dnskeysyncd` loaded fust fine!

**Comment by adelton** [comment]
```
# docker exec freeipa-server-container ls -la /etc/ipa/dnssec/ipa-dnskeysyncd.keytab
-r--r-----. 1 root ods 570 Mar 28 14:59 /etc/ipa/dnssec/ipa-dnskeysyncd.keytab
```

**Comment by frol** [comment]
Hmmm... It seems that my installation normalized even with odd permissions:

```
# docker exec -it freeipa_1 ls -la /etc/ipa/dnssec/ipa-dnskeysyncd.keytab
-r--r----- 1 memcached named 490 Apr 30  2015 /etc/ipa/dnssec/ipa-dnskeysyncd.keytab
```

I wish I never tried to force the upgrade process...

Thank you for your support!
