### ISSUE TITLE
Typo in ipa-client-configure-first

### ISSUE THREAD

**Issue by mmarzantowicz** [adelton/docker-freeipa#65]
I'm not sure but shouldn't this line (https://github.com/adelton/docker-freeipa/blob/client/ipa-client-configure-first#L75) in client be:
```
/usr/sbin/ipa-client-install [...] --no-nisdomain > /dev/null
```
instead of:
```
/usr/sbin/ipa-client-install [...] --no-nisdomain < /dev/null
```
I guess the intention was to redirect output to `/dev/null` not to read from it.

**Comment by adelton** [comment]
No. We invoke that ```ipa-client-install``` with ```-U``` so stdin is not (expected to be) used. On the other hand, we want to show the output of the command.
