### ISSUE TITLE
Synchronizing master-systemd with master

### ISSUE THREAD

**Issue by mmarzantowicz** [adelton/docker-freeipa#67]
Is it possible to sync `master-systemd` branch with `master`? After recent changes it (`master-systemd`) does not build at all. Manually applying changes from master fixes that issue. It also doesn't contain resolver improvements added previously in master.

**Comment by adelton** [comment]
Could you switch to using the `master` branch?

The `master-systemd` was a WIP branch where the systemd-in-container approach was developed but it now was merged to `master`, so my plan is to actually remove it, rather than keep it around.

**Comment by mmarzantowicz** [comment]
Thanks, I'm switching,

**Comment by adelton** [comment]
Thanks.
I've now purged that branch and amended `README` to point people to `master`.
