### ISSUE TITLE
Failed to execute operation: Too many levels of symbolic links

### ISSUE THREAD

**Issue by mmarzantowicz** [adelton/docker-freeipa#69]
I'm not sure what is the impact of this error message but it appears in `ipa-server-configure-first` file. Here is some more context (last few lines of log files).
```
Be sure to back up the CA certificates stored in /root/cacert.p12
These files are required to create replicas. The password for these
files is the Directory Manager password
Created symlink from /etc/systemd/system/container-ipa.target.wants/ipa-server-update-self-ip-address.service to /usr/lib/systemd/system/ipa-server-update-self-ip-address.service.
Created symlink from /etc/systemd/system/container-ipa.target.wants/ipa-server-upgrade.service to /usr/lib/systemd/system/ipa-server-upgrade.service.
Failed to execute operation: Too many levels of symbolic links
FreeIPA server configured.
```
It might be an error in (or line before when symlink is created by` systemctl`):
```
systemctl disable ipa-server-configure-first.service || rm -f /etc/systemd/system/multi-user.target.wants/ipa-server-configure-first.service
```
that is line 238 (https://github.com/adelton/docker-freeipa/blob/master/ipa-server-configure-first#L238).

I'm investigating this further but with no success so far.

**Comment by adelton** [comment]
It's a bug in `systemctl disable`: https://bugzilla.redhat.com/show_bug.cgi?id=1285996.
We workaround it so for the FreeIPA container it's just cosmetic.
