### ISSUE TITLE
restarting container results in not being able to contact KDC realm

### ISSUE THREAD

**Issue by slmingol** [adelton/docker-freeipa#7]
When I restart docker and the container I'll eventually run into an issue where I'm unable to connect to the KDC realm. When I enter the restarted container and attempt to run `kinit admin` I encounter this:

    kinit: Cannot contact any KDC for realm 'BUBBA.NET' while getting initial credentials

I suspect that when I restart docker I'm getting a new IP address for the container and this is causing an issue with configuration files such as /etc/resolv.conf, perhaps. I'll look into it further but was wondering if your script `/usr/sbin/ipa-server-configure-first` took this into account?

NOTE: looking through my container that resulted from the restart I noticed that it now has IP 172.17.0.5 but previously had 172.17.0.9 when looking through the log file /var/log/krb5kdc.log, for example.

**Comment by adelton** [comment]
The ipa-server-configure-first will update the DNS record for its own hostname in the DNS. If you manually set /etc/resolv.conf on the host running the FreeIPA container to point to the container, then yes, you will need to update it to match the new IP address.

Alternatively, you should be able to run the container with -p 53:53 -p 53:53/udp and point the /etc/resolv.conf to 127.0.0.1 or the IP address of the host -- iptables should route the traffic to the container then.

**Comment by slmingol** [comment]
I've been setting up the container like so:

    $ export IP=192.168.1.111; docker run -e IPA_SERVER_IP=$IP \
      -e FORWARDER=8.8.8.8 -p $IP:53:53/udp -p $IP:53:53 \
      -p $IP:80:80 -p $IP:443:443 -p $IP:389:389 -p $IP:636:636 -p $IP:88:88 -p $IP:464:464 \
      -p $IP:88:88/udp -p $IP:464:464/udp -p $IP:123:123/udp -p $IP:7389:7389 \
      --name ipa -ti -h ipa.bubba.net -e PASSWORD=secretpass centos/freeipa:latest

I'm able to restart it fine, but if I stop/start dockerd and then restart it and it doesn't get the same IP it won't start back up. Here's the output from the logs after restarting dockerd.

````
FreeIPA server is already configured, starting the services.
Starting [ntpd.service]
Starting [certmonger.service]
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
Starting [ipa-dnskeysyncd.service]
Starting [rhel-domainname.service]
domainname: you must be root to change the domain name
Starting [sssd.service]
Starting [ipa.service]
Existing service file detected!
Assuming stale, cleaning and proceeding
Starting Directory Service
Starting krb5kdc Service
Starting kadmin Service
Starting named Service
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 0.in-addr.arpa/IN: loaded serial 0
Starting ipa_memcached Service
Starting httpd Service
Starting pki-tomcatd Service
Failed to start pki-tomcatd Service
Shutting down
kill: sending signal to 190 failed: No such process
Java virtual machine used: /usr/lib/jvm/jre/bin/java
classpath used: /usr/share/tomcat/bin/bootstrap.jar:/usr/share/tomcat/bin/tomcat-juli.jar:/usr/share/java/commons-daemon.jar
main class used: org.apache.catalina.startup.Bootstrap
flags used: 
options used: -Dcatalina.base=/usr/share/tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/cache/tomcat/temp -Djava.util.logging.config.file=/usr/share/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
arguments used: stop
Aborting ipactl
kinit: Cannot contact any KDC for realm 'BUBBA.NET' while getting initial credentials
; Communication with 127.0.0.1#53 failed: timed out
could not talk to specified name server
FreeIPA server started.
Starting interactive shell.
````

**Comment by slmingol** [comment]
I just realized that you must have added `$IPA_SERVER_IP`  to your repo but the official image from the docker registry (hub.docker.com) is lacking this change. Currently downloading from your repo and rebuilding to see if that fixes my issue.

**Comment by adelton** [comment]
The images at https://registry.hub.docker.com/u/adelton/freeipa-server/ have been rebuilt.
