### ISSUE TITLE
[!!!!!!] Failed to mount API filesystems, freezing.

### ISSUE THREAD

**Issue by JoyceBabu** [adelton/docker-freeipa#72]
I am getting the error message

    [!!!!!!] Failed to mount API filesystems, freezing.

when I try to run 

    docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`/data:/data:Z --name freeipa-test -h ipa.example.test adelton/freeipa-server exit-on-finished

I tried removing the volume mounting options, but still it is showing the same error

**Comment by adelton** [comment]
What OS and docker version is this?

Did you build the image or did you get it from Docker Hub? Which branch/tag?

**Comment by JoyceBabu** [comment]
The host is `Ubuntu 15.10`. 

**Docker Info**
```
sysadmin@ennexa:~$ docker info
Containers: 20
 Running: 15
 Paused: 0
 Stopped: 5
Images: 305
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 614
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host weavemesh bridge null
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.7 GiB
Name: ennexa
ID: ZJIB:ZUVY:X7GR:R44F:UMW5:4MDV:PKFK:TYAU:OCFI:T55C:4J6F:Q2AK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
**Docker Version**

```
sysadmin@ennexa:~$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

I have tried both `adelton/freeipa-server:latest` and `adelton/freeipa-server:centos-7` images on DockerHub.

**Comment by adelton** [comment]
Could you try with different storage driver than aufs?

**Comment by JoyceBabu** [comment]
Is it possible to do that without affecting my existing containers?

**Comment by mmarzantowicz** [comment]
Please read Docker documentation about storage drivers at https://docs.docker.com/engine/userguide/storagedriver/selectadriver/ . In any case I strongly recommend that you have your data/containers backed up before making any changes to storage drivers (just in case). Each storage driver stores data under separate directory (`/var/lib/docker/<driver name>`), so it should not destroy your containers. It might be also possible to run more than one docker daemon simultaneously.

**Comment by adelton** [comment]
Closing now, please reopen if anything else is needed.

**Comment by CEbbinghaus** [comment]
I am encountering the same problem:
```
Failed to set RLIMIT_CORE: Operation not permitted
Failed to mount cgroup at /sys/fs/cgroup/systemd: No such file or directory
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...
```
This is happening even with the `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` argument pointed out in the Readme
https://github.com/freeipa/freeipa-container/blob/a6d0a99c1bf218ed79683489d140a19cc6678d52/README#L44-L45

My Storage Driver is `btrfs`

**Comment by adelton** [comment]
Can't you use some newer OS than Ubuntu 15.10? We no longer test on such old OS versions.

**Comment by CEbbinghaus** [comment]
This is not using Ubuntu. The Docker engine is running on Unraid 6.9 which is based on slackware

**Comment by adelton** [comment]
Ah. You said you had the same problem, so I though you have the same host OS. So it's a different situation and we will want it tracked separately.

Please open a new issue with this information. Also please check and show output of `tests/run-partial-tests.sh Dockerfile.almalinux-9`.

**Comment by CEbbinghaus** [comment]
> Please open a new issue with this information. Also please check and show output of tests/run-partial-tests.sh Dockerfile.almalinux-9.

Thanks I will create a new issue. I already ran the test and it failed due to `systemd` not running. Still investigating all that but I will track it all in a separate issue

**Comment by CEbbinghaus** [comment]
@adelton moved to #504
