### ISSUE TITLE
letsencrypt

### ISSUE THREAD

**Issue by joshuacox** [adelton/docker-freeipa#74]
Has anyone tried to integrate letsencrypt to generate the certs?

I see that it is certainly problematic:

https://www.redhat.com/archives/freeipa-users/2015-December/msg00025.html

but it seems like if anyone would be trying it, the docker images seem like a great place t o start hacking

**Comment by kforner** [comment]
+1

**Comment by JoyceBabu** [comment]
You can use letsencrypt for the http server.

https://github.com/freeipa/freeipa-letsencrypt/

**Comment by kforner** [comment]
good to know, thanks.

**Comment by joshuacox** [comment]
closing, that is great!
