### ISSUE TITLE
Failed to execute operation: Too many levels of symbolic links

### ISSUE THREAD

**Issue by typekpb** [adelton/docker-freeipa#79]
My setup ended with msg like this:

	Setup complete

	Next steps:
		1. You must make sure these network ports are open:
		        TCP Ports:
		          * 80, 443: HTTP/HTTPS
		          * 389, 636: LDAP/LDAPS
		          * 88, 464: kerberos
		          * 53: bind
		        UDP Ports:
		          * 88, 464: kerberos
		          * 53: bind
		          * 123: ntp

		2. You can now obtain a kerberos ticket using the command: 'kinit admin'
		   This ticket will allow you to use the IPA tools (e.g., ipa user-add)
		   and the web user interface.
		3. Kerberos requires time synchronization between clients
		   and servers for correct operation. You should consider enabling ntpd.

	Be sure to back up the CA certificates stored in /root/cacert.p12
	These files are required to create replicas. The password for these
	files is the Directory Manager password
	Created symlink from /etc/systemd/system/container-ipa.target.wants/ipa-server-update-self-ip-address.service to /usr/lib/systemd/system/ipa-server-update-self-ip-address.service.
	Created symlink from /etc/systemd/system/container-ipa.target.wants/ipa-server-upgrade.service to /usr/lib/systemd/system/ipa-server-upgrade.service.
	Failed to execute operation: Too many levels of symbolic links
	FreeIPA server configured.

What makes me a bit nervous is line: 

      Failed to execute operation: Too many levels of symbolic links

Is it a desired behaviour? Is it only specific to my setup?

**Comment by adelton** [comment]
It's a bug in `systemctl disable`: https://bugzilla.redhat.com/show_bug.cgi?id=1285996.
We workaround it with `|| rm -f ...` so for the FreeIPA container it's just cosmetic.

Also reported in https://github.com/adelton/docker-freeipa/issues/69.

**Comment by typekpb** [comment]
@adelton perfect, thanks
