### ISSUE TITLE
client + server fail to start in docker-compose setup

### ISSUE THREAD

**Issue by typekpb** [adelton/docker-freeipa#81]
Having `docker-compose.yml` file:

    version: "2"

    services:

      ipa: # [branch] master
        build:
          context: ./freeipa-server
          dockerfile: Dockerfile
        container_name: ipa
        ports:
          - "8389:389" # LDAP
          - "8636:636" # LDAPS
          - "8088:88" # kerberos
          - "8464:464" # kerberos
          - "8053:53" # bind
        hostname: server1.foo.bar.net
        domainname: foo.bar.net
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
          - ./freeipa-server/ipa-data:/data:Z
        environment:
          - PASSWORD=supersecretpassword

      ipa-client: # [branch] centos 7 client
        build: 
          context: ./freeipa-client
          dockerfile: Dockerfile
        container_name: ipa_client
        hostname: client1.foo.bar.net
        domainname: foo.bar.net
        depends_on:
          - ipa
        environment:
          - PASSWORD=supersecretpassword

once I run: `sudo rm -rf freeipa-server/ipa-data/ && docker-compose build && docker-compose up`, I see in console:

	Recreating ipa
	Recreating ipa_client
	Attaching to ipa, ipa_client
	ipa exited with code 123
	ipa_client    | Unable to discover domain, not provided on command line
	ipa_client    | Installation failed. Rolling back changes.
	ipa_client    | IPA client is not configured on this system.
	ipa_client exited with code 1

what am I doing wrong? As far as I can see, both sides (client as well as server have trouble)

For full project sample, see: https://github.com/typekpb/docker-freeipa/tree/sample-docker-compose

**Comment by typekpb** [comment]
for sample build run, see: https://travis-ci.org/typekpb/docker-freeipa/builds/135772764

**Comment by adelton** [comment]
I'd assume the IPA server container might not be happy about not having that `freeipa-server/ipa-data/` directory, or about SELinux type, if you are running this from your home directory.

You might want to check https://github.com/adelton/webauthinfra for an example multi-container setup.

**Comment by typekpb** [comment]
I'll try to adapt existing sample you referred to to my needs! Thanks a lot for feedback!

**Comment by adelton** [comment]
Closing now.
