### ISSUE TITLE
Configuration management system instead of arrays of bash scripts

### ISSUE THREAD

**Issue by rokka-n** [adelton/docker-freeipa#82]
Why bash script and not ansible? Is it for all the docker workaround?

**Comment by adelton** [comment]
Bash is installed by default in all base images. Ansible is not.

What workaround do you have in mind?

**Comment by rokka-n** [comment]
I mean workarounds mentioned in dockerfile and scripts:
https://github.com/adelton/docker-freeipa/blob/213c9ed30958dab9b6f93ec9d29c02312ff7b859/Dockerfile#L8

**Comment by adelton** [comment]
That is not really bash specific.

**Comment by adelton** [comment]
Closing now.
