### ISSUE TITLE
COPY Step: no such file or directory

### ISSUE THREAD

**Issue by ericbond007** [adelton/docker-freeipa#83]
When running docker build -t freeipa-server . using the current Dockerfile, I receive this error:

Step 12 : COPY init-data ipa-server-configure-first ipa-server-status-check exit-with-status ipa-volume-upgrade-* /usr/sbin/
lstat init-data: no such file or directory

I removed the "init-data" entry and ran again. I received a similar error, but this time for "ipa-server-configure-first"

**Comment by adelton** [comment]
Is `init-data` and `ipa-server-configure-first` in the directory in which you run that `docker build .` command?

**Comment by ericbond007** [comment]
No, those files are not in that directory. I didn't know they needed to be there. I didn't see anything in the readme about init-data.

**Comment by adelton** [comment]
The assumption is you clone the whole repository, not just the `Dockerfile`, and build from the working tree of that repository checkout.
