### ISSUE TITLE
Docker 1.12 issues (server and client don't work)

### ISSUE THREAD

**Issue by wyvie** [adelton/docker-freeipa#86]
Since docker 1.12 is finally released (and now has official repo for fedora 24), I've tried freeipa-server and client on this new version.

By default freeipa-server doesn't start and generates errors:
```
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

However, specifying unconfined seccomp profile (`--security-opt seccomp=unconfined` on `docker run` command) makes it start and install the freeipa server.

For whatever reason, client doesn't start:
```
Discovery was successful!
Client hostname: d581d16a0818.example.test
Realm: EXAMPLE.TEST
DNS Domain: example.test
IPA Server: ipa.example.test
BaseDN: dc=example,dc=test

Synchronizing time with KDC...
Attempting to sync time using ntpd.  Will timeout after 15 seconds
Unable to sync time with NTP server, assuming the time is in sync. Please check that 123 UDP port is opened.
In unattended mode without a One Time Password (OTP) or without --ca-cert-file
You must specify --force to retrieve the CA cert using HTTP
Cannot obtain CA certificate
HTTP certificate download requires --force
Installation failed. Rolling back changes.
```

If i add `--force` flag to `ipa-client-install`, i get this:
```
Discovery was successful!
Client hostname: d581d16a0818.example.test
Realm: EXAMPLE.TEST
DNS Domain: example.test
IPA Server: ipa.example.test
BaseDN: dc=example,dc=test

Synchronizing time with KDC...
Attempting to sync time using ntpd.  Will timeout after 15 seconds
Unable to sync time with NTP server, assuming the time is in sync. Please check that 123 UDP port is opened.
Downloading the CA certificate via HTTP, this is INSECURE
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=EXAMPLE.TEST
    Issuer:      CN=Certificate Authority,O=EXAMPLE.TEST
    Valid From:  Mon Aug 01 09:16:41 2016 UTC
    Valid Until: Fri Aug 01 09:16:41 2036 UTC

Joining realm failed: HTTP response code is 401, not 200

Use ipa-getkeytab to obtain a host principal for this server.
Please make sure the following ports are opened in the firewall settings:
     TCP: 80, 88, 389
     UDP: 88 (at least one of TCP/UDP ports 88 has to be open)
Also note that following ports are necessary for ipa-client working properly after enrollment:
     TCP: 464
     UDP: 464, 123 (if NTP enabled)
Failed to obtain host TGT: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639107): No credentials cache found
Installation failed. Force set so not rolling back changes.
```

Closer to working, but not there yet. Could you please help investigating the problem?

**Comment by adelton** [comment]
> Since docker 1.12 is finally released (and now has official repo for fedora 24), I've tried freeipa-server and client on this new version.

Looking at http://dl.fedoraproject.org/pub/fedora/linux/updates/24/x86_64/d/, there is only docker-1.10.3-26.git1ecb834.fc24.x86_64.rpm there so far.

**Comment by wyvie** [comment]
@adelton docker moved from official repos to their own repos some time ago. As far as I understand, new versions will never appear in official repos (until some enthusiasts do the work).
https://docs.docker.com/engine/installation/linux/fedora/ <- works for fedora 24

**Comment by adelton** [comment]
> https://docs.docker.com/engine/installation/linux/fedora/ <- works for fedora 24

It fails even during installation due to some SELinux mismatch, on fully upgrade Fedora 24 machine:

```
  Installing  : docker-engine-selinux-1.12.0-1.fc24.noarch                                      10/11 
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at /var/lib/selinux/targeted/tmp/modules/100/virt/cil:148
/usr/sbin/semodule:  Failed!
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.12.0-1.fc24.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux
  Installing  : docker-engine-1.12.0-1.fc24.x86_64                                                 11/11 
```

I would not call those build usable.

**Comment by adelton** [comment]
Even plain

```
docker run --rm -e container=docker -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run -ti fedora:24 /usr/sbin/init
```

fails with

```
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
Error response from daemon: No such container: 81c2c128a522c03e1861ddaf0a738f650f3c85980e21317dc3d28abec2ce4374
Error response from daemon: devmapper: Unknown device 97f881507cd236b271798f9a93dfdf79da45366cf5ce0c950234c8ca943d2d7b
```

I don't think it is worth spending time investigating these builds. Let's way for Docker 1.12 being properly packaged in Fedora.

**Comment by wyvie** [comment]
@adelton docker 1.11 has been released long ago, but never got to fedora repos. or debian repos. or any other linux distribution repos though.
if we wait for them to get into fedora repos, we'll be using 1.10 forever.
Since they renamed `docker` package to `docker-engine`, about a year has already passed.

It all happens because docker people for whatever reason don't public current version of their project on any page of their website at all.

Those fails are what i've been pointing to. These are about security profiles, which have been in docker since 1.11, they prevent using syscalls (more about that here: https://docs.docker.com/engine/security/seccomp/). For whatever reason setting volumes in Dockerfile makes it work though.

**Comment by mmarzantowicz** [comment]
This looks like what I have encountered in Arch Linux some time ago (see [issue 85](https://github.com/adelton/docker-freeipa/issues/84#issuecomment-232024639)). There is a temporary workaround - run containers with ` --security-opt seccomp=unconfined`.

BTW, this is not a FreeIPA isssue. It's docker's one.

**Comment by wyvie** [comment]
@mmarzantowicz I wrote about this workaround in the first post.
Still client doesn't work for whatever reason (works fine on 1.10 though). Do you consider it docker related, too?

**Comment by mmarzantowicz** [comment]
@wyvie as for the client it's a bit more complicated. What about your network and DNS settings? Maybe something isn't passed between client and server and it fails to setup properly. Pleas manually check with clean Fedora container that you can access all ports on IPA server (do some nmap or other scan). It helped me several times. I don't know if you're using `docker-compose` but it's nice and helps to provide reproducible configurations for containers, so I strongly recommend it. Finally, I wouldn't be surprised if your client issue is in some way related to docker and not Free IPA itself.

**Comment by wyvie** [comment]
@mmarzantowicz dns and network are okay, because on docker 1.10 everything works with the same configuration, but on 1.12 client doesn't connect to server.
I checked with clean configuration of fedora inside different vms with different configurations several days ago, everything works with 1.10, but with 1.12 it doesn't.
I know about docker-compose and use it in some projects, but here it is not that necessary.

I understand it might be related to docker, but I can't figure the problem myself, so I asked the question here.

**Comment by mmarzantowicz** [comment]
@wyvie two things come to my mind:

1. firewall settings (docker does some basic `iptables` setup)
1. seccomp policy blocks network related syscalls on your client container (try run it with seccomp disabled)

IMHO, after eliminating this two possibilities we can get back to Free IPA (high level :-) ) causes.

**Comment by dhilst** [comment]
Hi is this fixed?

I have this same problem. The cause was `--link freeipa-server-container:ipa` was creating an `ipa <IP>` line in /etc/hosts. The solution was using FQDN in `--link` option `--link freeipa-server-container:ipa.example.com`

Here is the how I've done. After building the images I created the containers like this. PS: I'm using unattended installation.

Server:

```
docker run --rm --name freeipa-server-container -ti -h master.example.com -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp --cap-add SYS_ADMIN --cap-add SYS_TIME freeipa-server -r EXAMPLE.COM -a secret -p secret --setup-dns --unattended --no-forwarders
```

Client:

```
docker run --rm --name freeipa-client-container -h nisimw.example.com --link freeipa-server-container:master.example.com -e PASSWORD=secret -e IPA_CLIENT_INSTALL_OPTS='--debug --force --domain example.com --server master.example.com' -ti freeipa-client
```
