### ISSUE TITLE
IPA services fail to start after building image

### ISSUE THREAD

**Issue by orodbhen** [adelton/docker-freeipa#9]
First of all, I should note that I'm pretty new to Docker.

I was able to build the image per the README, with one change. I tried to run it with all my settings:

    docker run --env=[IPA_SERVER=172.17.0.1,PASSWORD="mypasswd"] --name ipa-server -ti -h ipa.docker.lan -p 11080:80 -p 11081:443 freeipa-server

but I received the message:

    Start as docker run -h $FQDN_HOSTNAME -e PASSWORD=$THE_ADMIN_PASSWORD image

So I did that, and the IPA server installed with no problems. I committed the image, and then tried to run the new image to commit my other settings:
 
    docker stop <id>
    docker commit <id> freeipa-server
    docker run --name ipa-server -ti  -p 11080:80 -p 11081:443 freeipa-server

However, I got the following output, and the container crashed: 

    FreeIPA server is already configured, starting the services.
    Starting [ntpd.service]
    Starting [certmonger.service]
    No pidof for [/usr/sbin/ntpd] found in [ntpd.service.name]

Running the image again, with the entry point set to /bin/bash, I tried running "systemct start-enabled" manually, and received the same message minus the last line. "systemctl status ntpd" returned "active".

However, when I tried to open the webui, it couldn't find the page. I can manually run "systemctl start httpd", and ncat can connect to the external ports 11080 and 11081, but the browser can't find the host. Perhaps because IPA isn't running.

I tried creating a container from the image on dockerhub, with the instructions posted there. It seemed to build and run without problems. However, I still get "Server not found" for the webui. I am prompted to add an exception for the certificate, but that's it. I can't see how it's getting a certificate from a website that it can't find. 

Also, although I can connect to port 389 of the container using ncat, an ldapsearch query fails.

**Comment by adelton** [comment]
Can you try adding `--cap-add=SYS_TIME` option to `docker run`?

**Comment by adelton** [comment]
> ncat can connect to the external ports 11080 and 11081, but the browser can't find the host. Perhaps because IPA isn't running.

To find the host from the machine where you run the browser, you need to point the `resolv.conf` to the DNS server that knows about the IPA server, or put the hostname to `/etc/hosts`.

**Comment by adelton** [comment]
> IPA_SERVER=172.17.0.1

Are you sure the container will be allocated this IP address? You usually want to use this option when the whole host is supposed to run as the IPA server, so you will put the IP address of the host there, not IP address from the Docker container IP space.

**Comment by adelton** [comment]
> ldapsearch query fails

I assume the DNS is the biggest issue here -- possibly `ldapsearch` cannot find the server either.

**Comment by orodbhen** [comment]
> To find the host from the machine where you run the browser, you need to point the resolv.conf to the DNS server that knows about the IPA server, or put the hostname to /etc/hosts.

I'm still trying to figure out how name resolution works with Docker. I assume you mean that my local machine needs to know the address of physical machine that the IPA container is running on. I can confirm that it does.

> I assume the DNS is the biggest issue here -- possibly ldapsearch cannot find the server either.

I can log into the container using:

    docker exec -it ipa-server /bin/bash

and confirm that the IP address is 172.17.0.2. Then from the container host I do:

    [admin@airbuildserver ~]$ nc -v 172.17.0.2 389
    Ncat: Version 6.40 ( http://nmap.org/ncat )
    Ncat: Connected to 172.17.0.2:389.

Then I try:

    [admin@airbuildserver ~]$ ldapsearch -x -H ldap://172.17.0.2 uid=admin
    # extended LDIF                                                                                                    
    #                                                                                                                  
    # LDAPv3                                                                                                           
    # base <> (default) with scope subtree                                                                             
    # filter: uid=admin                                                                                                
    # requesting: ALL                                                                                                  
    #                                                                                                                  
                                                                                                                    
    # search result                                                                                                    
    search: 2                                                                                                          
    result: 32 No such object                                                                                          
                                                                                                                    
    # numResponses: 1
    
This command works on a phsyical IPA box I have running on another LAN, but perhaps the directory access permissions are different for this container.

**Comment by orodbhen** [comment]
Here's the output of `docker logs -f ipa-server`:

    FreeIPA server is already configured, starting the services.
    Starting [ntpd.service]
    Starting [certmonger.service]
    Starting [ipa-dnskeysyncd.service]
    Starting [fedora-domainname.service]
    domainname: you must be root to change the domain name
    Starting [sssd.service]
    Starting [ipa.service]
    Existing service file detected!
    Assuming stale, cleaning and proceeding
    Starting Directory Service
    Starting krb5kdc Service
    Starting kadmin Service
    Starting named Service
    zone localhost.localdomain/IN: loaded serial 0
    zone localhost/IN: loaded serial 0
    zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
    zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
    zone 0.in-addr.arpa/IN: loaded serial 0
    Starting ipa_memcached Service
    Starting httpd Service
    Starting pki-tomcatd Service
    Starting ipa-otpd Service
    Starting ipa-dnskeysyncd Service
    ipa: INFO: The ipactl command was successful
    ipa.docker.lan has address 172.17.0.2
    FreeIPA server started.
    Starting interactive shell

**Comment by orodbhen** [comment]
Running ldapsearch from the terminal in the container works:

    ldapsearch -x -h 127.0.0.1 uid=admin

Also, as I noted before, I can retrieve the certificate in the browser from my local machine, but I get "Server not found" after that.

I noticed that it redirects the host fqdn to the containers fqdn. I figured that the problem may be that it can't resolve the container's fqdn. So I added an entry mapping the containers FQDN to the hosts IP, and now I get a "Unable to connect error." 

So there seems to be some cryptic nuances of Docker networking at play here.

**Comment by orodbhen** [comment]
I rebuilt the image, and ran it with:

    docker run --name ipa-server2 -ti -h  ipa2.docker.lan -e PASSWORD="mypass" --cap-add=SYS_TIME -p 11080:80 -p 11081:443 freeipa-server

It now builds and runs with no problems. But I still can't connect to any of the services.

**Comment by orodbhen** [comment]
So ldapsearch actually works. I forgot that it needs the basedn specified, since the host isn't in docker.lan ldap domain. I still can't open the webui, though.

**Comment by adelton** [comment]
> I still can't open the webui, though.

What *exactly* do you try to do, from which machine?

**Comment by orodbhen** [comment]
I have a server that acts as the docker host. The freeipa container is running on it, with ports 80 and 443 mapped to ports 11080 and 11081 of the host, respectively.

From my workstation, I enter https://<physical server>:11080/ in Firefox, expecting it to bring up the IPA webui. I get redirected to ipa.docker.lan/ipa/ui, and it prompts me to add the security exception. I accept, but then I get a "Server not found."

DNS has no trouble resolving the physical server. I have another process installed on the host machine ( not a container ), that listens on port 80, and I have not trouble connecting to it.

I've also tried using a reverse proxy, instead of mapping the container port to a host port, with the same result. 

It seems to be a problem with the way apache redirects urls in the IPA container. I can access other containers running web interfaces from my workstation with no problems. I have the same issue when I try to download the server certificate from the host server:

    $ wget http://172.17.0.27/ipa/config/ca.crt
    --2015-01-23 16:05:54--  http://172.17.0.27/ipa/config/ca.crt
    Connecting to 172.17.0.27:80... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: http://ipa.docker.lan/ipa/config/ca.crt [following]
    --2015-01-23 16:05:54--  http://ipa.docker.lan/ipa/config/ca.crt
    Resolving ipa.docker.lan (ipa.docker.lan)... failed: Name or service not known.
    wget: unable to resolve host address ‘ipa.docker.lan’

**Comment by adelton** [comment]
As mentioned above, your best approach for initial debugging is to put the correct record to `/etc/hosts`. If you attempt to access the IPA from different machine than the host running the container, it needs to be the IP address of the host.
Alternatively, map the port 53 of the IPA server to port 53 (both TCP and UDP) on the host and set `/etc/resolv.conf` to point to the IP address of the host.
Another issue is, since the internal redirects that IPA uses will not preserve your custom port, you need to map the 443 to 443 on the host (and 80 to 80).

**Comment by orodbhen** [comment]
Alright. Thanks for the help. Unfortunately I don't think we're going to be able to use this solution. 

I was hoping to use the container to provide ldap authentication internally for services running on a development server. But it looks like this is still a long ways from stable.

I'll have to mess around with getting this working over time, and use a VM for now.
