### ISSUE TITLE
Error: image library/freeipa-server:latest not found

### ISSUE THREAD

**Issue by diversys** [adelton/docker-freeipa#90]
sudo docker run --name freeipa-server-container -ti    -h ipa.example.test    -v /sys/fs/cgroup:/sys/fs/cgroup:ro    -v ./ipa-data:/data:Z freeipa-server
Unable to find image 'freeipa-server:latest' locally
Pulling repository freeipa-server
Error: image library/freeipa-server:latest not found

**Comment by adelton** [comment]
Did you build the image, for example using

```
$ docker build -t freeipa-server .
```

?

**Comment by diversys** [comment]
Of course, as per instruction. I'm on CentOS 6.8 btw.
The only modification I did was 
```
rm Dockerfile
ln -s Dockerfile.centos-7 Dockerfile
```

I also created **ipa-data** in current directory instead of /var/lib/ipa-data.

**Comment by adelton** [comment]
If the ```docker build -t freeipa-server .``` command passed, what does ```docker images``` show?

**Comment by diversys** [comment]
```
sudo docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                   <none>              3fcc6b5ce62c        51 minutes ago      892 MB
adelton/freeipa-server   latest              76eb54310dd9        6 days ago          740 MB
fedora                   24                  daf0c008c194        6 days ago          204.4 MB
centos                   centos7             d83a55af4e75        3 weeks ago         196.7 MB
hello-world              latest              f0cb9bdcaa69        7 weeks ago         1.848 kB
```

**Comment by adelton** [comment]
So it looks like the `docker build` attempt failed -- you should likely rerun it and check the end of its output.

On the other hand you seem to have `adelton/freeipa-server` downloaded so you can just run the container from that image.

**Comment by diversys** [comment]
Trying to build again results in this error:
```
sudo docker build -t freeipa-server .
Step 31 : STOPSIGNAL
Unknown instruction: STOPSIGNA
```
Trying to run the container from that image just stops at this point:

```
sudo docker run adelton/freeipa-server
ls: cannot access '/sys/fs/cgroup': No such file or directory
```

uname -a
Linux tm14l 2.6.32-642.3.1.el6.centos.plus.x86_64 #1 SMP Tue Jul 12 18:28:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adelton** [comment]
Please upgrade to docker 1.9 which added support for `STOPSIGNAL`. Or just comment that line out from the Dockerfile, it's not essential.

As for the lack of `/sys/fs/cgroup` -- you might want to check https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/ch-Using_Control_Groups.html to see how to enable `cgconfig` service on RHEL 6. But truth be told, I never run docker nor docker-freeipa on RHEL/CentOS 6 host so I'm not sure how far that gets you.
