### ISSUE TITLE
build -t freeipa-server . fails to install httpd

### ISSUE THREAD

**Issue by diversys** [adelton/docker-freeipa#91]
Tried to run httpd **build -t freeipa-server .** on Debian 7.11 and got this error.

Dependency Updated:
  systemd.x86_64 0:219-19.el7_2.12     systemd-libs.x86_64 0:219-19.el7_2.12

Failed:
  httpd.x86_64 0:2.4.6-40.el7.centos.4

Complete!
The command '/bin/sh -c mkdir -p /run/lock && yum install -y ipa-server ipa-server-dns ipa-server-trust-ad && yum clean all' returned a non-zero code: 1

**Comment by adelton** [comment]
That seems similar to https://github.com/adelton/docker-freeipa/issues/22, https://github.com/adelton/docker-freeipa/issues/46, or https://github.com/adelton/docker-freeipa/issues/72. I assume your docker installation uses AUFS storage driver on which installation of the `httpd` package in the container fails. Please use different storage driver or different OS on the host which does not default to AUFS.
