### ISSUE TITLE
passing parms

### ISSUE THREAD

**Issue by choman** [adelton/docker-freeipa#93]
Wasn't really sure what to call this.  but using fedora and centos dockerfiles

Failed to install release agent, ignoring: File exists
Thu Oct  6 23:30:22 UTC 2016 /usr/sbin/ipa-server-configure-first 

The log file for this installation can be found in /var/log/ipaserver-install.log
ipa.ipapython.install.cli.install_tool(Server): ERROR    IPA server is already configured on this system.
If you want to reinstall the IPA server, please uninstall it first using 'ipa-server-install --uninstall'.

Please help he get around this, This was following the readme file, docker run ...

Update, think I figured out what is happening.  stand by.

**Comment by choman** [comment]
This was following the readme file, docker run ...

**Comment by adelton** [comment]
Out of curiosity, what was the cause?

**Comment by choman** [comment]
something in the data dir (/var/lib/ipa-data) was causing a conflict.  I nuked the directory contents and eventually got things working.  Barring my other submitted issue (ntp).  But I will keep those comments there.
